name: Fetch Images Every Day
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - code
  schedule:
    - cron: '0 16 * * *'
  repository_dispatch:
    types: [custom-event]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt


    - name: Run Python script
      run: |
        python3 main.py
        echo "All done!"

    - name: Commit files
      run: |
        git config --local user.email "thane.joss@gmail.com"
        git config --local user.name "thane joss"
        git add .
        git commit -m "Fetch Images"
        git push 
      
